### ISSUE TITLE
Type arguments for "tract_core::model::ModelImpl"

### ISSUE THREAD

**Issue by julama** [snipsco/tract#195]
I want to define a struct 'Model' but I get an error for type arguments. What is the correct way to use the 'ModelImpl' types?

```
struct Model {
            model: tract_core::model::ModelImpl,
            model_name: String,
        }

    let mut model_1 = Model {
        model: tract_tensorflow::tensorflow().model_for_path("mobilenet_v2_1.4_224_frozen.pb")?,
        model_name: String::from("model_1"),
    };
    
    let mut model = model_1.model;
```

When running the 'tract-mobilenet-v2-example' with the modification above I get the following error:

```
error[E0107]: wrong number of type arguments: expected 2, found 0
 --> examples/tensorflow-mobilenet-v2/src/main.rs:8:20
  |
8 |             model: tract_core::model::ModelImpl,
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 type arguments

```
Thanks!

**Comment by kali** [comment]
Hey, thanks for your interest in tract!

I'm not sure what you are trying to achieve here, ModelImpl is not meant to be used explicitely outside of tract. I suggest you make the field the InferenceModel. Or even better a TypedModel, so that you can call into_optimized() on the loaded model before moving it to your struct.

**Comment by julama** [comment]
Thank you! That works.
